schema_version: 1

context:
  version: "0.1.1"

package:
  name: xhycom
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/x/xhycom/xhycom-${{ version }}.tar.gz
  sha256: d86c05c838a9779997be1c011c193d6090ffa8dfecfc7d11473c9a5215d9f32f

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61
  run:
    - python >=${{ python_min }}
    - numpy
    - xarray
    - cftime
    - dask
    - xgcm >=0.10.1
    - numba
    - xesmf

tests:
  - python:
      imports:
        - xhycom
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/nansencenter/xhycom
  license: MIT
  license_file: LICENSE
  summary: xarray interface for HYCOM .ab binary output files
  documentation: https://xhycom.readthedocs.io
  repository: https://github.com/nansencenter/xhycom

extra:
  recipe-maintainers:
    - NoraLoose
